// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfOeQdLabkqVlghwcX3bmiTVprJTWEiXU',
    appId: '1:670271177322:web:d7cecf4c049e5ac73e4013',
    messagingSenderId: '670271177322',
    projectId: 'yoga-app-986b8',
    authDomain: 'yoga-app-986b8.firebaseapp.com',
    databaseURL: 'https://yoga-app-986b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yoga-app-986b8.firebasestorage.app',
    measurementId: 'G-RC87780PPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyf1vBGyWKfLjHjYLpWyrqiIYe8nqkJug',
    appId: '1:670271177322:android:668e50779ab1d4843e4013',
    messagingSenderId: '670271177322',
    projectId: 'yoga-app-986b8',
    databaseURL: 'https://yoga-app-986b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yoga-app-986b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'your-ios-api-key',
    appId: 'your-ios-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.flutterYoga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'your-macos-api-key',
    appId: 'your-macos-app-id',
    messagingSenderId: 'your-sender-id',
    projectId: 'your-project-id',
    storageBucket: 'your-project-id.appspot.com',
    iosBundleId: 'com.example.flutterYoga',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfOeQdLabkqVlghwcX3bmiTVprJTWEiXU',
    appId: '1:670271177322:web:d47aa29fb6ec9e623e4013',
    messagingSenderId: '670271177322',
    projectId: 'yoga-app-986b8',
    authDomain: 'yoga-app-986b8.firebaseapp.com',
    databaseURL: 'https://yoga-app-986b8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'yoga-app-986b8.firebasestorage.app',
    measurementId: 'G-KJNKXXDM2F',
  );

}